# Generated by Django 2.2.2 on 2019-09-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_getintouch'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GetInTouch',
            new_name='SendMessage',
        ),
    ]
