# Generated by Django 2.2 on 2019-09-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.TextField(default='Anonymous', max_length=30),
        ),
        migrations.AlterField(
            model_name='rating',
            name='comment',
            field=models.TextField(default='This was an awesome place!!', max_length=300),
        ),
    ]
