# Generated by Django 2.2 on 2019-09-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20190903_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='description',
            field=models.TextField(default='Awesome place!', max_length=1000),
        ),
    ]
