# Generated by Django 2.2.2 on 2019-09-03 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
